import { useState } from 'react'
import { jsPDF } from 'jspdf'
import Header from './Header'
import BottomNav from './BottomNav'

const FILTER_OPTIONS = ['All transactions', 'Fee', 'Transfer', 'Deposit', 'Withdrawal', 'Payment']

function fmt(dateStr) {
  const d = new Date(dateStr + 'T00:00:00')
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

// SVG Icons
const SearchIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
    <circle cx="11" cy="11" r="7" stroke="#003087" strokeWidth="2.2"/>
    <path d="M20 20l-3.5-3.5" stroke="#003087" strokeWidth="2.2" strokeLinecap="round"/>
  </svg>
)
const PrintIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
    <rect x="5" y="2" width="14" height="8" rx="1" stroke="#003087" strokeWidth="2"/>
    <rect x="3" y="10" width="18" height="10" rx="1" stroke="#003087" strokeWidth="2"/>
    <path d="M7 15h10M7 18h6" stroke="#003087" strokeWidth="1.8" strokeLinecap="round"/>
    <path d="M7 10V7" stroke="#003087" strokeWidth="2" strokeLinecap="round"/>
  </svg>
)
const DownloadIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
    <path d="M12 3v13M7 12l5 5 5-5" stroke="#003087" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"/>
    <path d="M3 19h18" stroke="#003087" strokeWidth="2.2" strokeLinecap="round"/>
  </svg>
)
const ChevronDown = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
    <path d="M6 9l6 6 6-6" stroke="#003087" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
)

export default function TransactionList({ transactions, currentBalance, onBack, onLogout }) {
  const [filter, setFilter] = useState('All transactions')
  const [showFilterMenu, setShowFilterMenu] = useState(false)
  const [showSearch, setShowSearch] = useState(false)
  const [searchText, setSearchText] = useState('')

  // Newest first
  const reversed = [...transactions].reverse()

  const visible = reversed.filter(tx => {
    const matchesType = filter === 'All transactions' || tx.type === filter
    const matchesSearch = !searchText || tx.description.toLowerCase().includes(searchText.toLowerCase())
    return matchesType && matchesSearch
  })

  const exportPDF = () => {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' })
    const pageW = doc.internal.pageSize.getWidth()
    const margin = 40
    let y = 50

    // Header bar
    doc.setFillColor(0, 48, 135)
    doc.rect(0, 0, pageW, 38, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(15)
    doc.setTextColor(255, 255, 255)
    doc.text('CHASE BUSINESS ACCOUNT', margin, 25)

    y = 60
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(60, 60, 60)
    doc.text(`Account: BUS COMP... (...9193)`, margin, y); y += 16
    const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    doc.text(`Export Date: ${today}`, margin, y); y += 24

    // Table header
    const cols = { date: 40, desc: 120, type: 310, amount: 380, balance: 460 }
    doc.setFillColor(0, 48, 135)
    doc.rect(margin - 4, y - 14, pageW - margin * 2 + 8, 20, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(255, 255, 255)
    doc.text('Date', cols.date, y)
    doc.text('Description', cols.desc, y)
    doc.text('Type', cols.type, y)
    doc.text('Amount', cols.amount, y)
    doc.text('Balance', cols.balance, y)
    y += 14

    // Rows (oldest first for PDF)
    const pdfRows = [...transactions]
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    pdfRows.forEach((tx, i) => {
      if (y > 760) { doc.addPage(); y = 50 }
      if (i % 2 === 0) {
        doc.setFillColor(240, 244, 252)
        doc.rect(margin - 4, y - 12, pageW - margin * 2 + 8, 16, 'F')
      }
      doc.setTextColor(50, 50, 50)
      doc.text(fmt(tx.date), cols.date, y)
      const descClipped = tx.description.length > 25 ? tx.description.slice(0, 23) + '…' : tx.description
      doc.text(descClipped, cols.desc, y)
      doc.text(tx.type || '', cols.type, y)
      const amtStr = (tx.amount >= 0 ? '+$' : '-$') + Math.abs(tx.amount).toFixed(2)
      doc.setTextColor(tx.amount >= 0 ? 46 : 200, tx.amount >= 0 ? 125 : 50, tx.amount >= 0 ? 50 : 50)
      doc.text(amtStr, cols.amount, y)
      doc.setTextColor(50, 50, 50)
      doc.text('$' + tx.balance.toFixed(2), cols.balance, y)
      y += 18
    })

    // Current balance footer
    y += 10
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(0, 48, 135)
    doc.text(`Current Balance: $${currentBalance.toFixed(2)}`, margin, y)

    y += 30
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(9)
    doc.setTextColor(150, 150, 150)
    doc.text('Generated by Chase Business Banking', margin, y)

    doc.save(`chase_statement_${Date.now()}.pdf`)
  }

  return (
    <div className="app">
      <div className="shell">
        <Header onSignOut={onLogout} />

        <div className="page-scroll">
          <div className="txns-page-title">Transactions</div>

          <div className="card" style={{ margin: '8px 16px' }}>
            {/* Toolbar */}
            <div className="txns-toolbar">
              <div className="txns-toolbar__left">
                <span>Showing</span>
                <div className="filter-dropdown">
                  <button
                    className="txns-toolbar__dropdown"
                    onClick={() => setShowFilterMenu(p => !p)}
                  >
                    {filter} ∨
                  </button>
                  {showFilterMenu && (
                    <div className="filter-dropdown__menu">
                      {FILTER_OPTIONS.map(opt => (
                        <button
                          key={opt}
                          className={`filter-dropdown__item${filter === opt ? ' filter-dropdown__item--selected' : ''}`}
                          onClick={() => { setFilter(opt); setShowFilterMenu(false) }}
                        >
                          {opt}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              <div className="txns-toolbar__icons">
                <button
                  className="txns-toolbar__icon-btn"
                  title="Search"
                  onClick={() => setShowSearch(p => !p)}
                >
                  <SearchIcon />
                </button>
                <button
                  className="txns-toolbar__icon-btn"
                  title="Print"
                  onClick={() => window.print()}
                >
                  <PrintIcon />
                </button>
                <button
                  className="txns-toolbar__icon-btn"
                  title="Export PDF"
                  onClick={exportPDF}
                >
                  <DownloadIcon />
                </button>
              </div>
            </div>

            {/* Search bar */}
            {showSearch && (
              <div className="txns-search-bar">
                <input
                  className="txns-search-input"
                  placeholder="Search by description…"
                  value={searchText}
                  onChange={e => setSearchText(e.target.value)}
                  autoFocus
                />
              </div>
            )}

            <hr className="txns-divider" />

            {/* Transaction list */}
            {visible.length === 0 && (
              <div className="txns-empty">No transactions found.</div>
            )}

            {visible.map((tx, i) => (
              <div key={tx.id}>
                <div className="txn-block">
                  <div className="txn-block__row">
                    <span className="txn-block__key">Date</span>
                    <span className="txn-block__val">{fmt(tx.date)}</span>
                  </div>
                  <div className="txn-block__row">
                    <span className="txn-block__key">Description</span>
                    <span className="txn-block__val txn-block__val--bold">{tx.description}</span>
                  </div>
                  <div className="txn-block__row">
                    <span className="txn-block__key">Type</span>
                    <span className="txn-block__val">{tx.type}</span>
                  </div>
                  <div className="txn-block__row">
                    <span className="txn-block__key">Amount</span>
                    <span className={`txn-block__val ${tx.amount >= 0 ? 'txn-block__val--green' : 'txn-block__val--red'}`}>
                      {tx.amount >= 0 ? '+$' : '-$'}{Math.abs(tx.amount).toFixed(2)}
                    </span>
                  </div>
                  <div className="txn-block__row">
                    <span className="txn-block__key">Balance</span>
                    <span className="txn-block__val">${tx.balance.toFixed(2)}</span>
                  </div>
                </div>
                {i < visible.length - 1 && <hr className="txns-divider" />}
              </div>
            ))}
          </div>
        </div>

        <BottomNav onBack={onBack} />
      </div>
    </div>
  )
}
